# Generated by Django 5.0.2 on 2025-04-04 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('color', models.CharField(choices=[('#808080', '灰色'), ('#ff6961', '赤色'), ('#ffb480', '橙色'), ('#f8f38d', '黄色'), ('#42d6a4', '緑色'), ('#08cad1', '水色'), ('#59adf6', '青色'), ('#9d94ff', '紫色'), ('#c780e8', '桃色')], max_length=30, verbose_name='現場色')),
                ('contract_type', models.CharField(choices=[('其他', '其他'), ('管理', '管理'), ('教练', '教练')], default='教练', max_length=50, verbose_name='职务')),
                ('fullname', models.CharField(blank=True, max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('email', models.CharField(blank=True, max_length=20, verbose_name='邮箱')),
                ('weixin', models.CharField(blank=True, max_length=20, verbose_name='微信')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Whatsapp')),
                ('line', models.CharField(blank=True, max_length=20, verbose_name='LINE')),
                ('tixi', models.CharField(choices=[('加拿大', '加拿大'), ('新西兰', '新西兰'), ('澳大利亚', '澳大利亚'), ('日本', '日本'), ('其他', '其他')], default='加拿大', max_length=50, verbose_name='体系')),
                ('jibie', models.CharField(choices=[('1级', '1级'), ('2级', '2级'), ('3级', '3级'), ('满级', '满级')], default='1级', max_length=50, verbose_name='级别')),
                ('sushe', models.CharField(blank=True, max_length=20, verbose_name='宿舍')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='現役中')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='客人姓名')),
                ('address', models.CharField(max_length=255, verbose_name='酒店')),
                ('jibie', models.CharField(max_length=255, verbose_name='级别')),
                ('job_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='内容')),
                ('payment_type', models.CharField(choices=[('現金', '現金'), ('カード', 'カード'), ('電子マネー', '電子マネー'), ('未支付', '未支付')], default='未支付', max_length=50, verbose_name='付款方式')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='付款金額')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='付款日')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('start_date', models.DateTimeField(verbose_name='開始日')),
                ('end_date', models.DateTimeField(verbose_name='終了日')),
                ('finished', models.BooleanField(default=False, verbose_name='終了')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('instructors', models.ManyToManyField(related_name='instructors', to='manager.profile')),
            ],
        ),
    ]
