# Generated by Django 5.1.8 on 2025-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='提成'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(choices=[('#808080', '灰色'), ('#ff6961', '赤色'), ('#ffb480', '橙色'), ('#f8f38d', '黄色'), ('#42d6a4', '緑色'), ('#08cad1', '水色'), ('#59adf6', '青色'), ('#9d94ff', '紫色'), ('#c780e8', '桃色')], max_length=30, verbose_name='教练色'),
        ),
    ]
