# Generated by Django 5.1.8 on 2025-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_profile_commission_alter_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='place',
            field=models.CharField(choices=[('比洛夫', '比洛夫'), ('花园', '花园'), ('安努', '安努'), ('莫伊哇', '莫伊哇'), ('留寿都', '留寿都'), ('喜乐乐', '喜乐乐')], default='比洛夫', max_length=50, verbose_name='雪场'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='payment_type',
            field=models.CharField(choices=[('現金', '現金'), ('刷卡', '刷卡'), ('電子支付', '電子支付'), ('未支付', '未支付')], default='未支付', max_length=50, verbose_name='付款方式'),
        ),
    ]
