# Generated by Django 5.1.8 on 2025-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_lesson_place_alter_lesson_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='jibie',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sushe',
            new_name='accommodation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jibie',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tixi',
        ),
        migrations.AddField(
            model_name='profile',
            name='ski',
            field=models.CharField(choices=[('双板无极', '双板无极'), ('双板1级', '双板1级'), ('双板2级', '双板2级'), ('双板3级', '双板3级'), ('双板4级', '双板4级')], default='双板1级', max_length=50, verbose_name='级别'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skisystem',
            field=models.CharField(choices=[('加拿大', '加拿大'), ('新西兰', '新西兰'), ('澳洲', '澳洲'), ('日本', '日本'), ('其他', '其他'), ('无', '无')], default='加拿大', max_length=50, verbose_name='双板体系'),
        ),
        migrations.AddField(
            model_name='profile',
            name='snowboard',
            field=models.CharField(choices=[('单板无极', '单板无极'), ('单板1级', '单板1级'), ('单板2级', '单板2级'), ('单板3级', '单板3级'), ('单板4级', '单板4级')], default='单板1级', max_length=50, verbose_name='级别'),
        ),
        migrations.AddField(
            model_name='profile',
            name='snowboardsystem',
            field=models.CharField(choices=[('加拿大', '加拿大'), ('新西兰', '新西兰'), ('澳洲', '澳洲'), ('日本', '日本'), ('其他', '其他'), ('无', '无')], default='加拿大', max_length=50, verbose_name='单板体系'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(choices=[('管理', '管理'), ('教练', '教练'), ('其他', '其他')], default='教练', max_length=50, verbose_name='职务'),
        ),
    ]
