# Generated by Django 5.1.8 on 2025-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_jibie_lesson_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skisystem',
            new_name='ski_system',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='snowboardsystem',
            new_name='snowboard_system',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='place',
            field=models.CharField(choices=[('比洛夫', '比洛夫'), ('花园', '花园'), ('安努', '安努'), ('莫伊哇', '莫伊哇'), ('留寿都', '留寿都'), ('喜乐乐', '喜乐乐'), ('其他', '其他')], default='比洛夫', max_length=50, verbose_name='雪场'),
        ),
    ]
