# Generated by Django 5.1.8 on 2025-04-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_skisystem_profile_ski_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='weixin',
            new_name='wechat',
        ),
    ]
