# Generated by Django 5.1.8 on 2025-04-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_weixin_profile_wechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='level',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(default=0, null=True, verbose_name='课次'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='邮箱'),
        ),
    ]
