# Generated by Django 5.1.8 on 2025-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_lesson_job_description_remove_lesson_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('初学', '初学'), ('初级', '初级'), ('中级', '中级'), ('上级', '上级'), ('导滑', '导滑')], default='初学', max_length=50, verbose_name='课程类型'),
        ),
    ]
